language: node_js
node_js:
- 10
install:
- yarn install --frozen-lockfile
script:
- yarn lint
- yarn build
- yarn test-ci
deploy:
  provider: npm
  email: frontend-dev@softwaremill.com
  api_key:
    secure: hGdmcET1Y8/5jxAifuSsZHgrSnAa4P3wV0NLzqK5o9Q/x25tVUkUaOgrHSiUprQKL4cAbe2hjw9g8bwMIfW3sbALoYC873BAFy8kjzilVTItWQdAVCXtCL45s+IG2FIy0eh27nIKZHfhlxvY69lB5pI/aZZ7l2DapsGArpqHG7WnLbLIZ2J7TiRbH59YA1pU3ecT0vVqrWpxmbzSvmagbDem1xibW8FLjmM4NTTbWVuoQuzppvQgzPlVyPmU20e/5LqDUk0jtMA/So/MOQZZAPH2WscCCoDt3RXKnBxLxpPedBNStRxbfrN4hGltYGFyB8O6udWkHD6Z4G+R33MkLXvtxW2hNnwD6tFDj98F6aIa/90jxhcNz8SXtU486IoE8dGHS8aLhf+NohrPpbH8g6+xVeirgjY0ISl6z73POIH9JnUKRiNWorxLr6DWbCpjcJ4cwLcsZHG5nCf26cy3r7nSMixyNMy+YTF8LMtat3vXcpKby3YGxD4wW6EpYIN4XD/41b3Kof5IUmgLiC9MPK/6LJl6KrdO87XAwuJBTwq/G3JGorWunoh7oDxZLQQPuqSMwE6JS9BFUPewYSGjjPmUyRWKRIBlU+o0ysIRmYl6IwojuYnP71yP9nrGB1jU0lspTo+ZBBbRixUZLl4OcpTn1pw8z3fKTry+SiNVVoM=
  on:
    tags: true
    repo: softwaremill/react-use-promise-matcher
